languageCode = "en-us"
title = "Matt Stewart"
baseurl = "https://mattstewart.io/"
theme = "aerial"

[params]
  name = "Matt Stewart"
  about = "Software Engineer &nbsp;&bull;&nbsp; Eagle River, AK"
  copyright = "2020 Matt Stewart"
  #Disable the scrolling background by entering any string for bg_scroll. Enable by leaving bg_scroll empty.
  bg_scroll = ""
  favicon = "favicon.png"

[[params.social]]
  medium = "LinkedIn"
  icon = "linkedin"
  link = "https://www.linkedin.com/in/mattstewart01/"

[[params.social]]
  medium = "Github"
  icon = "github"
  link = "https://github.com/mattstewart"

[[params.social]]
  medium = "Email"
  icon = "file-o"
  link = "https://share.mattstewart.io/MattStewartResume.pdf"

[[params.social]]
  medium = "Email"
  icon = "envelope-o"
  link = "mailto:hello@mattstewart.io"
